### ISSUE TITLE
Would be nice if state was sorted by "since date"

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#30]
When sorting by state it would be nice if items with the same state would sort by "since date", this way it'd be easier checking with are the latest submited, etc.
![state_col](https://cloud.githubusercontent.com/assets/9051674/15558630/9ef8503c-22db-11e6-9632-d78d8be7376b.png)

**Comment by tsdgeos** [comment]
If you give me a hint of where the change may be i'll gladly try to fix it myself.

**Comment by ancorgs** [comment]
I'll take a closer look tomorrow, but I can give you some hints if you want to try. DISCLAIMER: Ruby on Rails gibberish ahead.

Sorting and searching is implemented using the ransack gem.
In the models you can use a scope to define any sorting criteria, then you can tell ransack to use that scope instead of the "state" attribute by just changing the corresponding column header in the view.
