### ISSUE TITLE
Disable the "Create comment" button after pressing it

### ISSUE THREAD

**Issue by tsdgeos** [openSUSE/travel-support-program#37]
The publishing of a comment is a bit slow and sometimes people think "this didn't work" and press the button again and again.

We just got 4 comments with the same content because of that.

Maybe would make sense to disable it while posting and maybe change the text to "Posting..." or something similar?

**Comment by krngrvr09** [comment]
@tsdgeos I think the publishing of the comment appears to be slow because we are not explicitly closing the modal after clicking ``Create comment``. That's why the modal stays there until the page loads. 

If we use the rails feature of disabling the submit button using ``:data => {:disable_with=>"Creating..."}``, then we get the following behaviour:
![output](https://cloud.githubusercontent.com/assets/5905966/24343717/85ee896c-12e5-11e7-98ed-7a4acd74b1a8.gif)

So I think a better way would be to explicitly close the modal before redirecting to a different page.

**Comment by tsdgeos** [comment]
If that's fine for Ancor it's fine for me :)

**Comment by krngrvr09** [comment]
@ancorgs What do you think?
